spring:
  application:
    name: ssp-mtls-client

server:
  port: 9001
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:ssp-mtls-client.jks
    key-store-password: password
    key-alias: ssp-mtls-client
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:ssp-mtls-client.jks
    trust-store-password: password
    trust-store-type: JKS

endpoint:
  ms-service: https://localhost:9002/ssp-mtls-server/data