version: '3.8'

services:
  db:
    image: 'postgres:latest'
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=oauth2
    ports:
      - 5431:5432

  adminer:
    image: 'adminer:latest'
    restart: always
    ports:
      - 6080:8080